# Generated by Django 6.0.4 on 2026-05-05 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'task', 'verbose_name_plural': 'tasks'},
        ),
    ]
